sudo: required
language: java
jdk: 
  - oraclejdk8
services:
  - docker
cache:
  directories:
  - $HOME/.m2
after_script:
  cat /tmp/dockerTestLogs/*

#addons:
#  apt:
#    packages:
#      - oracle-java8-installer
