sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker
cache:
  directories:
  - $HOME/.m2
script:
  - ./mvnw test -B
  - bash <(curl -s https://codecov.io/bash)
after_script:
  - cat /tmp/dockerTestLogs/*

#addons:
#  apt:
#    packages:
#      - oracle-java8-installer
